version: '3.8'
services:
  postgres:
    image: postgres
    container_name: marcinho-excursoes-backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marcinhotest
    restart: always
    ports:
      - "5400:5432"